config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'

  resources :recipes do
    resources :ingredients
    resources :steps
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :steps
end

app/models/step.rb
class Step < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build(ingredient_params)

    respond_to do |format|
      if @ingredient.save(ingredient_params)
        format.html { redirect_to recipe_path(@recipe) }
        format.json { render :show, status: :created, title: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])

    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, title: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])

    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
  end

  private

  def set_ingredient
    @recipe = Recipe.find(params[:recipe_id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:count, :name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.page(params[:page]).per(10)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to recipes_path }
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, title: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, title: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.build(step_params)

    respond_to do |format|
      if @step.save(step_params)
        format.html { redirect_to recipe_path(@recipe) }
        format.json { render :show, status: :created, title: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])

    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @recipe, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, title: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])

    @step.destroy
    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
  end

  private

  def set_step
    @recipe = Recipe.find(params[:recipe_id])
  end

  def step_params
    params.require(:step).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/_form.html.erb
<%= form_with( model: [recipe, ingredient], local: true, class: 'ingredient-form' ) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field(:count, in: 1.0..20.0, step: 0.5) %>
  </div>

  <!--  measurment field -->

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', recipe: @recipe, ingredient: @ingredient %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path(@recipe) %>

app/views/ingredients/new.html.erb
<h1><%= @recipe.title  %></h1>
<p><%= @recipe.description %></p>

<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient, recipe: @recipe %>

<%= link_to 'Back', recipe_path(@recipe) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PgRecipeBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true, class: 'recipe-form') do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipe Box - Recipes</h1>
<%= link_to 'New Recipe', new_recipe_path %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @recipes %>
<%= page_entries_info @recipes %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<body class="recipe_show">
  <h1><%= @recipe.title %></h1>

  <p>
    <%= @recipe.description %>
  </p>

  <h3>Ingredients</h3>
  <%= link_to 'Add Ingredient', new_recipe_ingredient_path(@recipe) %>
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
    <li>  <%= ingredient.count %> <%= ingredient.name %> <%= link_to 'Delete', recipe_ingredient_path(@recipe, ingredient), method: :delete, data: { confirm: "Are you sure?"} %> <%= link_to 'Edit', edit_recipe_ingredient_path(@recipe, ingredient) %></li>
    <% end %>
  </ul>

  <h3>Steps</h3>
  <%= link_to 'Add Step', new_recipe_step_path(@recipe) %>
  <ol>
    <% @recipe.steps.each do |step| %>
    <li> <%= step.description %> <%= link_to 'Delete', recipe_step_path(@recipe, step), method: :delete, data: { confirm: "Are you sure?"} %> <%= link_to 'Edit', edit_recipe_step_path(@recipe, step) %> </li>
    <% end %>
  </ol>

  <%= link_to 'Recipes', recipes_path %>
  <%= link_to 'Delete', @recipe, method: :delete, data: { confirm: "Are you sure?"} %>
</body>

app/views/steps/_form.html.erb
<%= form_with(model: [recipe, step], local: true, class: 'step-form') do |form| %>
  <% if step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_step_description%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form', recipe: @recipe, step: @step %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path(@recipe) %>

app/views/steps/new.html.erb
<h1><%= @recipe.title  %></h1>
<p><%= @recipe.description %></p>

<h1>New Cooking Step</h1>

<%= render 'form', step: @step, recipe: @recipe %>

<%= link_to 'Back', recipe_path(@recipe) %>